更新 Github Actions 配置

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -115,10 +115,16 @@ jobs:
         run: |
           $exe_orig = Get-ChildItem -Path target -Filter "*.exe" | Select-Object -First 1
           $exe_base = $exe_orig.BaseName
-          $exe_new = "${exe_base}_x64_windows.exe"
-          Rename-Item -Path $exe_orig.FullName -NewName $exe_new
-          $exe_new_path = Join-Path $exe_orig.Directory $exe_new_name
-          echo "exe_file=$exe_new_path" >> $env:GITHUB_OUTPUT
+          $exe_new_name = "${exe_base}_x64_windows.exe"
+          Rename-Item -Path $exe_orig.FullName -NewName $exe_new_name
+          $exe_new = Get-ChildItem -Path $exe_orig.Directory -Filter $exe_new_name | Select-Object -First 
+          
+          if (-not $exe_new) {
+            Write-Error "Renamed file not found"
+            exit 1
+          }
+          $exe_path = $exe_new.FullName -replace '\\', '/'
+          echo "exe_file=$exe_path" >> $env:GITHUB_OUTPUT
 
       - name: Upload Windows .exe to Release
         if: github.event_name == 'release'
